import Foundation

enum Copy {
    private static let zh: [String: String] = [
        "schedule": "课表",
        "courses": "课程",
        "settings": "设置",
        "add": "添加",
        "edit": "编辑",
        "save": "保存",
        "cancel": "取消",
        "delete": "删除",
        "previous": "上一周",
        "today": "本周",
        "next": "下一周",
        "courseCode": "课程代码",
        "courseName": "课程名称",
        "location": "地点",
        "notes": "备注",
        "link": "课程链接",
        "courseType": "课程类型",
        "recurrence": "重复方式",
        "days": "星期",
        "date": "日期",
        "start": "开始时间",
        "end": "结束时间",
        "color": "颜色",
        "semester": "学期",
        "language": "语言",
        "density": "显示密度",
        "compact": "紧凑",
        "comfortable": "标准",
        "roomy": "宽松",
        "lecture": "Lecture",
        "tutorial": "Tutorial",
        "lab": "Lab",
        "seminar": "Seminar",
        "workshop": "Workshop",
        "other": "Other",
        "weekly": "每周",
        "biweekly": "每两周",
        "monthly": "每月",
        "once": "单次日期",
        "noCourses": "还没有课程",
        "newCourse": "新课程",
        "currentSemester": "当前学期",
        "active": "进行中",
        "archive": "归档",
        "createSemester": "新建学期",
        "cannotSave": "无法保存",
        "requiredName": "课程名称不能为空。",
        "invalidTime": "结束时间必须晚于开始时间。",
        "selectDay": "请选择至少一个星期。",
        "weekRange": "周范围",
        "prototypeNote": "iOS 原生版原型"
    ]

    private static let en: [String: String] = [
        "schedule": "Schedule",
        "courses": "Courses",
        "settings": "Settings",
        "add": "Add",
        "edit": "Edit",
        "save": "Save",
        "cancel": "Cancel",
        "delete": "Delete",
        "previous": "Previous",
        "today": "This Week",
        "next": "Next",
        "courseCode": "Course Code",
        "courseName": "Course Name",
        "location": "Location",
        "notes": "Notes",
        "link": "Course Link",
        "courseType": "Course Type",
        "recurrence": "Recurrence",
        "days": "Days",
        "date": "Date",
        "start": "Start",
        "end": "End",
        "color": "Color",
        "semester": "Semester",
        "language": "Language",
        "density": "Display Density",
        "compact": "Compact",
        "comfortable": "Comfortable",
        "roomy": "Roomy",
        "lecture": "Lecture",
        "tutorial": "Tutorial",
        "lab": "Lab",
        "seminar": "Seminar",
        "workshop": "Workshop",
        "other": "Other",
        "weekly": "Weekly",
        "biweekly": "Every Two Weeks",
        "monthly": "Monthly",
        "once": "One Date",
        "noCourses": "No courses yet",
        "newCourse": "New Course",
        "currentSemester": "Current Semester",
        "active": "Active",
        "archive": "Archive",
        "createSemester": "New Semester",
        "cannotSave": "Cannot Save",
        "requiredName": "Course name cannot be empty.",
        "invalidTime": "End time must be later than start time.",
        "selectDay": "Select at least one weekday.",
        "weekRange": "Week Range",
        "prototypeNote": "Native iOS prototype"
    ]

    static func text(_ key: String, _ language: Language) -> String {
        switch language {
        case .zh:
            return zh[key] ?? en[key] ?? key
        case .en:
            return en[key] ?? zh[key] ?? key
        }
    }
}
